---
- name: Add openjdk-r/ppa PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
    mode: '0644'
    update_cache: yes

- name: Install OpenJDK package
  apt:
    name:
      - ca-certificates-java
      - openjdk-{{ openjdk_version }}-jre
    state: present
