---
- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

# Workaround for Let's Encrypt root certificate expiration
# https://scotthelme.co.uk/lets-encrypt-old-root-expiration
- name: Install latest ca-certificates package version
  apt:
    name: ca-certificates
    state: latest

- name: Install basic packages
  apt:
    name:
      # Contains htpasswd
      - apache2-utils
      - apt-transport-https
      # Install make and other useful compilation tools
      - build-essential
      - curl
      - gnupg
      - htop
      - jq
      # Package to configure locale
      - locales
      # Use python3 if a "python" command is issued
      - python-is-python3
      # Allow ansible SSH connection using password
      - sshpass
      - tmux
      - unzip
      - zip
    state: present

- name: NO COWS ALLOWED HERE (just like in Diablo :p)
  copy:
    src: 'ansible.sh'
    dest: '/etc/profile.d/ansible.sh'
    mode: '0644'

- name: Configure locale variables
  template:
    src: 'locale'
    dest: '/etc/default/locale'
    mode: '0644'

- name: Set timezone to the one set in vars.yml
  timezone:
    name: "{{ user_timezone }}"

- name: Activate timedatectl synchronisation
  command: timedatectl set-ntp true
