---
- name: Check go install
  stat:
    path: '/usr/local/go/bin'
  register: go_bin

- name: Check go installed version
  shell:
    cmd: /usr/local/go/bin/go version | sed -n -e 's/go version go\([0-9\.]*\) .*$/\1/p'
  register: go_installed_version
  when: go_bin.stat.exists
  changed_when: false

- name: Delete existing go install to update
  file:
    path: '/usr/local/go'
    state: absent
  when: go_bin.stat.exists and (go_installed_version.stdout != go_version)

- name: Untar go archive
  unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-{{ architecture_instructions }}.tar.gz"
    remote_src: yes
    dest: '/usr/local/'
    mode: '0755'
  when: not go_bin.stat.exists or (go_installed_version.stdout != go_version)

- name: Change permissions on go bin directory
  file:
    path: '/usr/local/go/bin'
    state: directory
    mode: '0777'
    recurse: yes
  when: not go_bin.stat.exists or (go_installed_version.stdout != go_version)

- name: Create the src folder inside GOPATH
  file:
    path: "{{ go_projects_path }}/src"
    state: directory
    mode: '0755'
    owner: "{{ main_user }}"
    group: "{{ main_user }}"

- name: Store go environment variables system-wide
  template:
    src: 'go.sh'
    dest: '/etc/profile.d/go.sh'
    mode: '0644'
