---
- name: Check yq install
  stat:
    path: "/usr/local/bin/yq"
  register: yq_bin

- name: Check yq installed version
  shell:
    cmd: 'yq --version | sed -n -e "s/yq .* version v\([0-9\.]*\)$/\1/p"'
  register: yq_installed_version
  when: yq_bin.stat.exists
  changed_when: false

- name: Install yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_{{ architecture_instructions }}"
    dest: "/usr/local/bin/yq"
    mode: "0755"
    force: yes
  when: not yq_bin.stat.exists or yq_installed_version.stdout != yq_version
