---
- name: Add git-core PPA
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    mode: '0644'
    update_cache: yes

- name: Install git from PPA
  apt:
    name: git
    state: present

- name: Add git-lfs gpg key to trusted keys
  get_url:
    url: 'https://packagecloud.io/github/git-lfs/gpgkey'
    dest: '/etc/apt/trusted.gpg.d/git-lfs.gpg'
    mode: '0644'
    force: yes

- name: Add git-lfs apt-repository
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/git-lfs.gpg] https://packagecloud.io/github/git-lfs/ubuntu jammy main'
    state: present
    mode: '0644'
    update_cache: yes

- name: Install git-lfs
  apt:
    name: git-lfs
    state: present
  register: lfs

- name: Run git-lfs installer
  shell:
    cmd: git lfs install
  when: lfs.changed
