---
- name: Add git-core PPA
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    mode: '0644'
    update_cache: yes

- name: Install git from PPA
  apt:
    name: git
    state: present

- name: Add git-lfs gpg key to trusted keys
  apt_key:
    id: '6D398DBD30DD78941E2C4797FE2A5F8BDC282033'
    url: 'https://packagecloud.io/github/git-lfs/gpgkey'
    keyring: '/etc/apt/trusted.gpg.d/git-lfs.gpg'
    state: present

- name: Add git-lfs apt-repository
  apt_repository:
    repo: 'deb https://packagecloud.io/github/git-lfs/ubuntu jammy main'
    state: present
    mode: '0644'
    update_cache: yes

- name: Install git-lfs
  apt:
    name: git-lfs
    state: present
  register: lfs

- name: Run git-lfs installer
  shell:
    cmd: git lfs install
  when: lfs.changed
