---
- hosts: "*"
  become: true

  pre_tasks:
    - name: Include relevant variables
      include_vars:
        file: "./vars.yml"
      tags:
        - always

  roles:
    - { role: basics, tags: ['basics'] }
    - { role: git, tags: ['git'] }
    - { role: ansible_lint, tags: ['ansible-lint'] }
    - { role: yq, tags: ['yq'] }
    - { role: terraform, tags: ['terraform'] }
    - { role: terragrunt, tags: ['terragrunt'] }
    - { role: awscli, tags: ['awscli'] }
    - { role: sops, tags: ['sops'] }
    - { role: vault, tags: ['vault'] }
    - { role: docker, tags: ['docker'] }
    - { role: kubernetes, tags: ['kubernetes'] }
    - { role: kustomize, tags: ['kustomize'] }
    - { role: minikube, tags: ['minikube'] }
    - { role: k9s, tags: ['k9s'] }
    - { role: kubeseal, tags: ['kubeseal'] }
    - { role: helm, tags: ['helm'] }
    - { role: velero, tags: ['velero'] }
    - { role: vals, tags: ['vals'] }
    - { role: go, tags: ['go'] }
    - { role: editorconfig, tags: ['editorconfig'] }
