---
- name: Check terragrunt install
  stat:
    path: "/usr/local/bin/terragrunt"
  register: terragrunt_bin

- name: Check terragrunt installed version
  shell:
    cmd: terragrunt -v | sed -n -e 's/terragrunt version v\(.*\)$/\1/p'
  register: terragrunt_installed_version
  when: terragrunt_bin.stat.exists
  changed_when: false

- name: Install terragrunt
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_{{ architecture_instructions }}"
    dest: "/usr/local/bin/terragrunt"
    mode: "0755"
    force: yes
  when: not terragrunt_bin.stat.exists or terragrunt_installed_version.stdout != terragrunt_version
